### ISSUE TITLE
Changing one byte in the sig leads to a new valid sig!

### ISSUE THREAD

**Issue by ebuchman** [haltingstate/secp256k1-go#7]
I have found cases where changing a single byte in a signature yields a new valid signature (ie I can recover a _different_ public key). Unless I'm missing something, this is critical.

I've started a repo to investigate this: https://github.com/ebuchman/secp256k1-tests/

See, in particular, https://github.com/ebuchman/secp256k1-tests/blob/master/main_test.go#L33

EDIT: I should note I'm using obscuren's fork, but looking more closely at the differences and trying to replicate on yours now.

**Comment by ebuchman** [comment]
Ok so from a new randomized test which tries randomly changing a random byte, it looks like about half the time we get a new valid sig :(

**Comment by ebuchman** [comment]
I have confirmed this is true for both repos, and even if using `SignDeterministic`. See branch `halting` in https://github.com/ebuchman/secp256k1-tests/

**Comment by ebuchman** [comment]
In more news, looks like about a quarter of utterly random sets of 65 bytes are valid signatures on an independent random sequence of 32 bytes. 

https://github.com/ebuchman/secp256k1-tests/blob/halting/main_test.go#L78

Is ECRECOVER just flat out insecure? I will take another look at the recover arithmetic.

**Comment by ebuchman** [comment]
Not sure why I thought this was a problem but after thinking about it all day I finally realize its seemingly no different than randomly guessing at private keys. Apologies if I've wasted your time.

**Comment by haltingstate** [comment]
>I have found cases where changing a single byte in a signature yields a new valid signature (ie I can recover a different public key). Unless I'm missing something, this is critical.

Good eye! Most people miss this completely.

Yes. You cant just check that a compressed signature is "valid". Just because you can recover a public key does not mean its valid! You need to check the signature against a hash and then check the recovered signature against a known signature!

So to validate a signature you need
- a public key to check it against
- or have to check the recovered public key against what the public key should hash to.

So someone can send you SHA256(PUBKEY) and then a message HASH = SHA256(MSG). Then a signature. Then you extract the pubkey for the signature, from the hash. Then verify that the SHA256 of the PUBKEY matches what you expect.

- If you just check if you can recover a pubkey, then its not valid. It does not mean anything. People do this sometimes and they do not check against failure cases, only positive unit tests, so they miss that their implementation does this. Validity of signature is not that you can recover a pubkey, but that the recovered pubkey for a given hash matches a known pubkey (or something that can be computed from the known pubkey).
- If you put the pubkey hash or pubkey itself outside of the message block its not valid. Someone can just modify it. I am sure someone has done this.
- If you place the pubkey hash or the pubkey itself in the message block, before hashing, then you can verify the signature from the message and no one can modify the message without invalidating the signature.

**Comment by ebuchman** [comment]
ok well ethereum for example does not include the pubkey or hash(pubkey) in txs, it just recovers the pubkey from the sig and goes from there. As far as I can tell, any recovered pub key is a valid point on the curve, and since secp256k1 has cofactor=1, any recovered pubkey is a potentially valid pubkey that could have been generated from a private key.

So I'm not sure what the problem would be then. What issues would ethereum have by not including the pubkey or hash of it in the tx?

**Comment by haltingstate** [comment]
nothing. the output is associated with an address which give you a pubkey
hash
